### ISSUE TITLE
Move docs into the repository

### ISSUE THREAD

**Issue by pavithraes** [Point72/csp#112]
**Is your feature request related to a problem? Please describe.**

Using GitHub wiki for docs doesn't allow us to have "reviews" in the documentation contribution workflow.

**Describe the solution you'd like**

Move the wiki pages into the repository as markdown files, and create an action that moves text over to the wiki. This means we'll treat the wiki as a read-only space.

This also allows us to have linting and testing to ensure consistency.

**Describe alternatives you've considered**

A docs website is the ideal solution, but is currently not do-able. However, having docs in the repo will allow easier transition to a docs generator if/when that happens.

**Additional context**

This was discussed with @ptomecek and @robambalu in a meeting today.

**Next steps:**

- [ ] Move the documentation **as-is** into the repo
- [ ] Give attribution fairly - add everyone who originally authored the docs as co-authors on the PR
- [ ] Add automation action

**Comment by poldpold** [comment]
Adding the documentation to the repo would allow me to submit a PR to fix #125 .
