### ISSUE TITLE
Documentation: explain "ticking"

### ISSUE THREAD

**Issue by melissawm** [Point72/csp#131]
I suggest adding some documentation on the concept of ticking.

- Why and how it is used
- How it is detected in common usage

This could be a section on the Getting Started guide (see #65)

**Comment by pavithraes** [comment]
Yes, covering this in getting started :)

**Comment by pavithraes** [comment]
Added some notes about ticking in [first steps page](https://github.com/Point72/csp/wiki/First-Steps), closing this issue as complete.
