### ISSUE TITLE
Expand, organize examples and find new sample data sources

### ISSUE THREAD

**Issue by melissawm** [Point72/csp#15]
The current set of [examples](https://github.com/Point72/csp/tree/main/csp/examples) can be improved. They need to be triaged into either experience levels (such as "beginner", "intermediate", "advanced") and/or by document type (such as How-tos, Tutorials, or API usage example).

The examples can also be refined to contain more comments and make context clearer, ideally connecting with the corresponding API documentation.

Lastly, it would be interesting to find new sample data sources to use in the examples.

**Comment by AdamGlustein** [comment]
We have quite a comprehensive set of examples now which are broken down by experience level, so I'm going to close this out.
