### ISSUE TITLE
Exceptions in CppNode impls do not show trace or node information

### ISSUE THREAD

**Issue by wrieg123** [Point72/csp#158]
**Describe the bug**
When an exception is raised within the cpp implementation of a node, there is no pertinent information about the node or trace from where the exception occurred.

**To Reproduce**
```c++
DECLARE_CPPNODE(my_impl) {
TS_INPUT(Generic, x);
INIT_CPPNODE(my_impl);
INVOKE() {
  if(csp.ticked(x)) {
    throw;
  }
};
};
EXPORT_CPPNODE(my_impl);
```
```python
@csp.node(cppimpl=_lib.my_impl)
def my_impl(x: ts['T']):
    if csp.ticked(x):
         return
```
Raise an exception within the cpp implementation of a node.

**Expected behavior**
Have some kind of traceback or pertinent information about the node which raises the exception.

**Error Message**
```Traceback (most recent call last):                                                                                                                  
File "/run.py", line 117, in <module>
    csp.run(g, starttime=datetime.utcnow(), realtime=True)                                                                                         
 File "/home/svcccagqa/include/csp/csp/impl/wiring/runtime.py", line 183, in run                                                                     
    with ExceptionContext():
  File "/home/svcccagqa/include/csp/csp/impl/error_handling.py", line 40, in __exit__                                                                 
              raise exc_val.with_traceback(new_tb)                                                                                                          
Exception: [SOME EXCEPTION]```

**Comment by AdamGlustein** [comment]
If you use `CSP_THROW` (https://github.com/Point72/csp/blob/main/cpp/csp/core/Exception.h#L80) instead of `throw` you should be able to see a stack trace

**Comment by wrieg123** [comment]
Right. The example above would be more related to an external dependency for the node raising the exception internally. It would not necessarily use csp_throw inherently.

**Comment by AdamGlustein** [comment]
In a user-defined node, if they call into external functions which they know can throw exceptions they should be catching those exceptions and rethrowing with `CSP_THROW`. When we throw exceptions from csp they need to be valid Python exception types i.e. ValueError, TypeError so I don't see how we could make a generic `throw;` return useful information. 

If you set `csp.impl.error_handling.set_print_full_exception_stack( True )` do you at least get a stack now?

**Comment by wrieg123** [comment]
Fair enough, ill try that
