### ISSUE TITLE
AdapterManager support is not currently available in dynamic graphs

### ISSUE THREAD

**Issue by Roh-codeur** [Point72/csp#287]
Hi

I have been using this package. truly amazing, also thanks for the docs

**Is your feature request related to a problem? Please describe.**
1. I am setting up a graph which sources in tickers from a source
2. Depending on the ticker, I subscribe to market data (via adapter)
3. I am using a Dynamic graph. this graph has a node which gives me the node
4. When the graph gets a ticker, I create a graph(to be included in Dynamic Graph) which uses Adapter Manager to create a market data subscription
5. At this point, I get the below error:

`NotImplementedError: AdapterManager.cpp:AdapterManager:19:NotImplemented: AdapterManager support is not currently available in dynamic graphs`

**Describe the solution you'd like**
Is there some way we can support AdapterManager in DynamicGraphManager please? 

**Describe alternatives you've considered**
Actually, it's a bit tricky to get data from a db/messaging bus without an AdapterManager - can you please suggest an alternate solution pls?

ta!

**Comment by timkpaine** [comment]
This is somewhat related to #277, as we need to enhance our adapter to have a pattern where dynamic subscriptions are more native. Right now most adapters expect all connections to be resolved at graph-building-time, and this is a pretty unrealistic expectation as your example plainly illustrates.

Will leave this open as separately, adapters should support dynamic regardless of #277.

**Comment by Roh-codeur** [comment]
got it, I understand. in the meantime, Can you suggest a workaround for this please? ta!

**Comment by robambalu** [comment]
At this point in time you would need to know your ticker universe up front, or "over subscribe" to all possible tickers.

**Comment by Roh-codeur** [comment]
thanks for looking into this. this is an excellent library - thanks for making it open source. This functionality is quite essential to my current project, I will keep an eye for this when it's a part of the library. ta!
