### ISSUE TITLE
Explain duplicate timestamps

### ISSUE THREAD

**Issue by pavithraes** [Point72/csp#291]
CSP has a many-to-1 mapping between timestamps and engine cycle. This allows for duplication of timestamps in the same engine cycle, for specific use cases. This needs to be documented, potentially in https://github.com/Point72/csp/wiki/Execution-Modes.

An example (shared by rob);

```python
def g():
    u = csp.unroll(csp.const.using(T=[int])([1, 2, 3]))
    s = csp.sample(csp.const(True), u)
    csp.print('u', u)
    csp.print('s', s)
csp.run(g, starttime=datetime(2024, 1, 1))
> 2024-01-01 00:00:00 u:1
> 2024-01-01 00:00:00 s:1
> 2024-01-01 00:00:00 u:2
> 2024-01-01 00:00:00 u:3
```

`csp.unroll` is also used in the [seismology example](https://github.com/Point72/csp/blob/main/examples/07_end_to_end/seismic_waveform.ipynb)

**Comment by AdamGlustein** [comment]
https://github.com/Point72/csp/wiki/Execution-Modes#csppushmode

Seems like this is appropriately documented.

**Comment by robambalu** [comment]
The request here was to document the nuances / gotchas of having dup timestamps, ie in the example mentioned above the sample may not behave the way one would naively expect
