### ISSUE TITLE
Mention type validation for `csp.graph`

### ISSUE THREAD

**Issue by pavithraes** [Point72/csp#295]
Add a note about strict type annotation and validation for `csp.graph` (in addition to `csp.node`) in:
- https://github.com/Point72/csp/wiki/CSP-Graph
- https://github.com/Point72/csp/wiki/First-Steps

**Comment by timkpaine** [comment]
Also good to note the difference between a graph-annotated python function, and a non annotated function, as well as [known issues](https://github.com/Point72/csp/issues/183)
