### ISSUE TITLE
Missing file in ```csp.lib``` for websocket

### ISSUE THREAD

**Issue by johnmatters03** [Point72/csp#298]
```_websocketadapterimpl``` is missing from ```csp.lib```. 

The examples from ```examples/03_using_adapters/websocket``` tries to import it but cannot find it in the path and causes an error.

To reproduce, install csp and run either examples for the websocket adapters.

**Comment by robambalu** [comment]
@johnmatters03 Can you please include the following information:
- What OS are you running on
- What version of csp you have installed

**Comment by johnmatters03** [comment]
@robambalu The OS I am running on is Windows 11 Home, with Python version 3.12.4. 
The csp I installed is version 0.0.4.
It seems like the basic examples work just fine.

**Comment by robambalu** [comment]
Thanks for that.  IT looks like websocket support on windows didn’t make the 0.0.4 cut, but its available in main
I’ll cut a release shortly, 0.0.5 should have it

**Comment by johnmatters03** [comment]
Thanks for the fix!

**Comment by robambalu** [comment]
fyi, 0.0.5 is out now
