### ISSUE TITLE
`csp.add_graph_output` wrong signature suggestion by editor

### ISSUE THREAD

**Issue by timkpaine** [Point72/csp#307]
relates to:
- https://github.com/Point72/csp/issues/82
- https://github.com/Point72/csp/issues/129

Example (VS Code):
<img width="338" alt="Screenshot 2024-06-28 at 20 39 50" src="https://github.com/Point72/csp/assets/3105306/7dd95aa9-686e-4fd4-9e70-3075cb2f602a">

**Comment by ptomecek** [comment]
I linked the PR to close this issue, but it's worth testing it will actually fix the editor suggestions on VSCode (which I don't use).

**Comment by timkpaine** [comment]
This doesn't seem to change anything

**Comment by ptomecek** [comment]
So the first commit only fixed calling `help(csp.add_graph_output)`. I just added type hint stubs for `csp.add_graph_output` and `csp.const` which allows static type checkers (and hence the IDE autocomplete) to pick up the signatures. I tested on PyCharm, please let me know if it works now on VSCode.

**Comment by timkpaine** [comment]
nice! clever with the stub
<img width="930" alt="Screenshot 2024-07-16 at 15 03 28" src="https://github.com/user-attachments/assets/84215c62-f26c-4c20-832c-ffe5ca0c7b9e">
