### ISSUE TITLE
Deprecated use of setup.py in Makefile

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Point72/csp#31]
I noticed deprecated use of `python setup.py sdist` and `python setup.py bdist_wheel` in the [Makefile](https://github.com/Point72/csp/blob/main/Makefile).

Seems that we should be using `python -m build` instead according to https://packaging.python.org/en/latest/discussions/setup-py-deprecated/.

**Comment by timkpaine** [comment]
Unfortunately it's not quote so straightforward, we will need to move to e.g. scikit-build-core so this is a longer term effort. It is more likely we will pin to a specific setup tools for the time being
