### ISSUE TITLE
Update to libprotobuf 5+

### ISSUE THREAD

**Issue by timkpaine** [Point72/csp#367]
https://github.com/conda-forge/csp-feedstock/pull/38

Should wait for https://github.com/conda-forge/pytorch-cpu-feedstock/pull/265

**Comment by wrieg123** [comment]
Does the libprotobuf version need to be pinned somewhere? I'm seeing [test build(s) fail](https://github.com/Point72/csp/actions/runs/11298146172/job/31426479589?pr=371) with `libprotobuf.dylib` version 5.27.5.

seems like this was flagged [here](https://github.com/conda-forge/csp-feedstock/pull/38#issuecomment-2385950081).
