### ISSUE TITLE
Remove macos 12 builds from our full CI pipeline

### ISSUE THREAD

**Issue by AdamGlustein** [Point72/csp#406]
**Describe the bug**

**To Reproduce**

macos12 is deprecated on GH Actions runner as of today: https://github.com/actions/runner-images/issues/10721.
As a result, full CI runs which use macos12 as part of the matrix are failing.

**Expected behavior**

**Error Message**

**Runtime Environment**

**Additional context**

We need to either remove macos 12 from the workflow or replace it with macos 13. I'm not sure how useful it will be to test 13 and 14, though.

**Comment by AdamGlustein** [comment]
We could also do macos 13/15 (instead of 12/14) in our full CI runs - @timkpaine

**Comment by timkpaine** [comment]
> We could also do macos 13/15 (instead of 12/14) in our full CI runs - @timkpaine

Note that we use macOS 12 for `x86` and 14 for `arm64`. I believe we can use the same version for both x86 and arm64, 14 or 15 is probably fine so long as we target a suitably old Mac target (`13.0` or earlier)
