### ISSUE TITLE
Document minimum machine requirements to build from source

### ISSUE THREAD

**Issue by ngoldbaum** [Point72/csp#48]
I'm trying to build `csp` in a VM with 4 GB of RAM and it keeps getting killed by the OOM killer. We should figure out how much RAM is actually needed on the build host and document that.

**Comment by ngoldbaum** [comment]
This is probably related to `make build` defaulting to 8 cores.

**Comment by timkpaine** [comment]
yeah I have a block of code for this::

```
UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
NPROC = $(shell nproc)
endif
ifeq ($(UNAME), Darwin)
NPROC = $(shell sysctl -n hw.physicalcpu)
endif
```
