### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by pavithraes** [Point72/csp#64]
As the release processes are updated, we need to document the new workflow to release on PyPI and conda-forge for current and future maintainers.

_(Originally noted by @ptomecek, @ngoldbaum, and @trallard)_

## Items to be included 

- Git for maintainers
	- Make `origin` your fork, set `upstream` to the real repo, add remotes for collaborators as needed
	- How to check out a PR locally
	- Dealing with old unmerged PRs (pushing fixups to other people's forks, when to do this and when not to)
	- Setting up commit signing and adding signing keys to github
- Github for maintainers
	- Triaging issues
	- Code review guidelines and checklist
	- Communication guidelines
- Doing a "normal" release
	- Choosing a new version number
	- Generating an author list from `git`
	- Writing release notes
- Tagging the release and pushing to github
	- Dealing with a release mistakes
	- Yanking for completely broken releases
	- Post releases for metadata fixes (e.g. a readme fix or to fix version constraints)
	- Permanent deletion for publishing private data, but this should be avoided
	- Doing a new release with a fix

Additional items that need documenting:
- versioning approaches (SemVer)

**Comment by ngoldbaum** [comment]
This is done now.
