### ISSUE TITLE
Inconsistent cmake version used when trying to build csp

### ISSUE THREAD

**Issue by AdamGlustein** [Point72/csp#73]
**Describe the bug**
When following the steps outlined in "Building with Conda on Linux", I observed the following build error. The build failed because the cmake version was less than 3.20.0; however, upon some debugging, it seems the wrong cmake version is being pulled in by skbuild. 

```
(csp) $ which cmake
.../github/csp_venv/envs/csp/bin/cmake
(csp) $ cmake --version
cmake version 3.28.3
```

Then, upon attempting the build (make build), I get the following error:

```
CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.20.0 or higher is required.  You are running version 3.13.5
```

Printing out the cmake/version being used I get:
```
Path to cmake: /usr/bin/cmake3
Cmake version: 3.13.5
```

It seems that skbuild is using the wrong cmake, different from what is specified by my PATH.

**To Reproduce**

**Expected behavior**
`make build` should pull in the correct cmake binary and succeed

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.3.1611 (Core)

**Comment by ngoldbaum** [comment]
The [sciki-build docs](https://scikit-build.readthedocs.io/en/latest/usage.html#usage-scikit-build-options) say that you can pass `--cmake-executable` to `setup.py`.

Can you try replacing the the content of the `build-py` rule in your local copy of the makefile with:

```
python setup.py build build_ext --inplace -- -- -j$(NPROC) --cmake-executable $HOME/github/csp_venv/csp/bin/cmake 
```

If that fails, could you share the shell output from the failed `make build` invocation?

I know I asked you to do something similar earlier, but I think I might have given you an incorrect command and if it doesn't work your shell output might have useful info.

**Comment by ngoldbaum** [comment]
Ultimately the `/usr/bin/cmake3` is coming from [this line](https://github.com/scikit-build/scikit-build/blob/bbd0bd0436d85951386292c3413027d4364319d7/skbuild/constants.py#L27) I think.

Here's what I think is happening. @AdamGlustein has `cmake3` installed from a system package but `cmake` installed from `conda-forge`. It looks like the conda-forge package doesn't create a `cmake3` symlink, so `scikit-build` finds `cmake3` on your PATH before it finds the conda-forge cmake, and uses that.

I *think* it will also work if you create a symlink from the conda-forge `cmake` binary to a new `cmake3` in the same bin directory.

This smells like a scikit-build bug to me, at the least it would be nice to be able to configure the cmake executable with an environment variable or something.

**Comment by AdamGlustein** [comment]
@ngoldbaum directly specifying the cmake executable pulled in the correct `cmake` and resulted in me being able to run `make build` and `make develop` without any errors, thanks!
