### ISSUE TITLE
Allow csp nodes to be defined in IPython

### ISSUE THREAD

**Issue by ptomecek** [Point72/csp#88]
**Is your feature request related to a problem? Please describe.**
At the moment, you can't define a csp node interactively in ipython (need to be part of an importable script)

Defining the following in IPython
```python
@csp.node
def f(x: csp.ts[int]) -> csp.ts[int]:
    return x
```
Throws
> OSError: could not get source code

**Describe the solution you'd like**
Ideally we should be able to define them in ipython, but at the very least, the error message should be a bit more helpful (i.e. explaining that defining nodes interactively is not supported yet)

**Comment by timkpaine** [comment]
That code works for me without error:

![image](https://github.com/Point72/csp/assets/3105306/b3977a0d-e189-47d2-b0e7-bbc3342ee40a)

**Comment by ptomecek** [comment]
So it does (when I run ipython from command line), so it seems like it's an IDE problem on my end. Will close.

**Comment by ogarokpeter** [comment]
Hi team!

I have a fresh reproduction of this that happens when running Python from command line. I get the same error as described above.

```
Python 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:46:58)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import csp
>>> import pandas
>>> from datetime import datetime
>>> @csp.graph
... def foo(x: pandas.DataFrame):
...   pass
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/csp/csp/impl/wiring/graph.py", line 393, in graph
    return _impl(func)
  File "/csp/csp/impl/error_handling.py", line 37, in __exit__
    raise exc_val.with_traceback(new_tb)
OSError: could not get source code
>>>
```

**Comment by timkpaine** [comment]
@ogarokpeter That looks like Python REPL, not IPython. Please open a separate issue to improve the error message in a REPL (or if a fix is possible, fix it in REPL). Looks like everything works a s expected in IPython.
