### ISSUE TITLE
Images in "Exponential Moving Statistics" section of csp.stats wiki not rendering properly. 

### ISSUE THREAD

**Issue by ptomecek** [Point72/csp#89]
The images linked here are not rendering properly: https://github.com/Point72/csp/wiki/2.-Statistics-Nodes-%28csp.stats%29/#exponential-moving-average

**Comment by AdamGlustein** [comment]
Seems the Confluence to Markdown converter I used converted LaTeX to an image, so anywhere there is LaTeX in the docs this will likely be an issue.
